"""
LLM-Assisted Explainable Radiology Report Generation Using Diagnostic Questioning
Phase 0.6 — Diagnostic QA Evaluation Module

Module: evaluate_qa.py
Purpose:
- Compares structured QA output (from vision model candidates & QA evaluation) against report-derived ground truth.
- Measures:
  1. Finding overlap (matched findings, missed findings, extra findings).
  2. Presence agreement (yes-yes, no-no, uncertain-uncertain).
  3. Location agreement for matched positive findings.
  4. Severity agreement for matched positive findings.

DISCLAIMER:
Metrics computed in this module measure information alignment between the research QA prototype
and rule-extracted report representations. They are technical evaluation metrics, NOT clinical diagnostic accuracies.
"""

import sys
from typing import Dict, List, Any, Tuple

# Ensure UTF-8 output on Windows consoles
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


def evaluate_qa_against_ground_truth(
    qa_output: Dict[str, Any],
    ground_truth_data: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Compare structured QA findings against report ground truth.

    Args:
        qa_output: Dictionary containing 'qa_findings' generated by DiagnosticQAEngine.
        ground_truth_data: Dictionary containing 'ground_truth_findings' from report_parser.

    Returns:
        Dictionary of comparison metrics and detailed alignment records.
    """
    qa_findings = qa_output.get("qa_findings", [])
    gt_findings = ground_truth_data.get("ground_truth_findings", [])

    qa_map = {f["finding"]: f for f in qa_findings}
    gt_map = {f["finding"]: f for f in gt_findings}

    all_evaluated_findings = set(qa_map.keys()).union(set(gt_map.keys()))

    matched_findings = []
    presence_matches = 0
    presence_mismatches = 0
    location_matches = 0
    severity_matches = 0

    missed_findings = []   # In Ground Truth, but not evaluated in QA
    extra_findings = []    # Evaluated in QA, but not present in Ground Truth

    comparison_details = []

    for name in all_evaluated_findings:
        qa_item = qa_map.get(name)
        gt_item = gt_map.get(name)

        if qa_item and gt_item:
            # Finding exists in both
            qa_pres = qa_item.get("presence", "uncertain").lower()
            gt_pres = gt_item.get("presence", "uncertain").lower()

            pres_agree = (qa_pres == gt_pres)
            if pres_agree:
                presence_matches += 1
            else:
                presence_mismatches += 1

            # Check location agreement if both present
            qa_loc = qa_item.get("location", "unspecified").lower()
            gt_loc = gt_item.get("location", "unspecified").lower()
            loc_agree = (qa_loc == gt_loc)
            if loc_agree and qa_pres == "yes":
                location_matches += 1

            # Check severity agreement if both present
            qa_sev = qa_item.get("severity", "unspecified").lower()
            gt_sev = gt_item.get("severity", "unspecified").lower()
            sev_agree = (qa_sev == gt_sev)
            if sev_agree and qa_pres == "yes":
                severity_matches += 1

            matched_findings.append(name)
            comparison_details.append({
                "finding": name,
                "status": "matched_evaluation",
                "qa_presence": qa_pres,
                "gt_presence": gt_pres,
                "presence_agreement": pres_agree,
                "qa_location": qa_loc,
                "gt_location": gt_loc,
                "qa_severity": qa_sev,
                "gt_severity": gt_sev,
                "qa_model_score": qa_item.get("model_score")
            })

        elif gt_item and not qa_item:
            # Ground truth documented a finding that QA engine did not select
            gt_pres = gt_item.get("presence", "uncertain").lower()
            missed_findings.append(name)
            comparison_details.append({
                "finding": name,
                "status": "missed_by_qa_selection",
                "qa_presence": None,
                "gt_presence": gt_pres,
                "presence_agreement": False,
                "gt_location": gt_item.get("location", "unspecified"),
                "gt_severity": gt_item.get("severity", "unspecified"),
                "qa_model_score": None
            })

        elif qa_item and not gt_item:
            # QA engine evaluated a finding unmentioned in ground truth report
            qa_pres = qa_item.get("presence", "uncertain").lower()
            extra_findings.append(name)
            comparison_details.append({
                "finding": name,
                "status": "evaluated_not_in_report",
                "qa_presence": qa_pres,
                "gt_presence": None,
                "presence_agreement": False,
                "qa_location": qa_item.get("location", "unspecified"),
                "qa_severity": qa_item.get("severity", "unspecified"),
                "qa_model_score": qa_item.get("model_score")
            })

    total_matched = len(matched_findings)
    presence_agreement_rate = (presence_matches / total_matched) if total_matched > 0 else 0.0

    evaluation_report = {
        "study_id": qa_output.get("study_id"),
        "total_qa_evaluated": len(qa_findings),
        "total_ground_truth_findings": len(gt_findings),
        "matched_findings_count": total_matched,
        "matched_findings_list": matched_findings,
        "missed_findings_count": len(missed_findings),
        "missed_findings_list": missed_findings,
        "extra_findings_count": len(extra_findings),
        "extra_findings_list": extra_findings,
        "presence_matches": presence_matches,
        "presence_mismatches": presence_mismatches,
        "presence_agreement_rate": round(presence_agreement_rate, 4),
        "comparison_details": comparison_details,
        "evaluation_notes": (
            "Presence agreement measures exact consistency between QA finding presence "
            "and rule-based report ground truth. Model scores are candidate triggers, not clinical facts."
        )
    }

    return evaluation_report
