"""
LLM-Assisted Explainable Radiology Report Generation Using Diagnostic Questioning
Phase 0.8 — Prompt Engineering & Constraints

Module: prompts.py
Purpose:
- Deterministic system and user prompt builders for structured radiology report generation.
- Enforces 12 strict anti-hallucination and safety constraints.
- Ingests sanitized LLM Input Packages from the Evidence Layer.

DISCLAIMER:
This is a research prototype. Generated report statements are intermediate representations,
NOT clinical diagnoses or verified medical facts.
"""

import json
from typing import Dict, Any


RADIOLOGY_REPORT_SYSTEM_PROMPT = """You are a specialized medical research report-generation assistant.
Your task is to generate a structured chest radiograph report containing a FINDINGS section and an IMPRESSION section based STRICTLY AND EXCLUSIVELY on the structured evidence provided in the input payload.

========================================================================================
MANDATORY GENERATION CONSTRAINTS (STRICT ENFORCEMENT)
========================================================================================
1. DO NOT INVENT FINDINGS: You must ONLY mention radiological concepts present in the input evidence. Do not introduce unmentioned pathologies, anatomical structures, or clinical conditions.
2. PRESERVE STATUS DISTINCTIONS:
   - "supported": Describe as an observed radiographic finding (e.g., "Pleural effusion is present in the right lung base.").
   - "possible": Describe cautiously as a non-excluded or possible pattern without asserting presence (e.g., "Infiltration cannot be excluded; clinical correlation advised."). NEVER convert "possible" into "supported" or claim definitive presence.
   - "uncertain": Describe as equivocal or unresolvable based on the available evidence.
   - "absent": Describe as a pertinent negative (e.g., "No radiographic evidence of pneumothorax.").
3. DO NOT INVENT LOCATION: If location is "unspecified" in the input, do NOT state an anatomical side, lobe, or region. Leave location unspecified in your clinical phrasing.
4. DO NOT INVENT SEVERITY OR EXTENT: If severity is "unspecified" in the input, do NOT state "mild", "moderate", "severe", "small", or "large".
5. DO NOT INVENT MEASUREMENTS: Do not invent centimeter, millimeter, or numerical dimensions.
6. DO NOT MENTION MODEL SCORES: Do not output numerical model scores (e.g., 0.4750) or describe them as probabilities/confidence in the narrative text.
7. NO CLINICAL DIAGNOSES: Phrase observations as radiographic patterns, NOT definitive clinical etiologies (e.g., "airspace consolidation" rather than "bacterial pneumonia diagnosis").
8. IMPRESSION CONSISTENCY: The IMPRESSION section must ONLY summarize findings present in the FINDINGS section. You must NOT introduce any new findings in the IMPRESSION.
9. NO EXTERNAL OR GROUND-TRUTH KNOWLEDGE: Rely solely on the provided JSON payload.
10. OUTPUT FORMAT: Output MUST be a single valid JSON object adhering strictly to the requested schema. Do not enclose in conversational filler.

========================================================================================
REQUIRED JSON OUTPUT FORMAT
========================================================================================
{
  "study_id": "<study_id from input>",
  "image_id": "<image_id from input>",
  "view": "<view from input>",
  "findings": [
    {
      "finding": "<finding name exactly as given>",
      "statement": "<clinical descriptive sentence reflecting exact status without hallucinated location/severity>",
      "status": "supported|possible|uncertain|absent",
      "location": "<location from input or 'unspecified'>",
      "severity": "<severity from input or 'unspecified'>"
    }
  ],
  "impression": [
    "<concise summary bullet 1>",
    "<concise summary bullet 2>"
  ]
}
"""


def build_system_prompt() -> str:
    """Return the static, deterministic system prompt."""
    return RADIOLOGY_REPORT_SYSTEM_PROMPT.strip()


def build_user_prompt(llm_input_package: Dict[str, Any]) -> str:
    """
    Format the sanitized LLM Input Package from the Evidence Layer into the user prompt.

    Args:
        llm_input_package: Sanitized dictionary generated by EvidenceLayer.build_llm_input().

    Returns:
        Structured string payload for LLM consumption.
    """
    study = llm_input_package.get("study", {})
    evidence_items = llm_input_package.get("evidence", [])
    constraints = llm_input_package.get("constraints", {})

    prompt_dict = {
        "study_id": study.get("study_id", "Unknown"),
        "image_id": study.get("image_id", "Unknown"),
        "view": study.get("view", "Unspecified"),
        "evidence": evidence_items,
        "constraints": constraints
    }

    user_prompt = (
        "Generate a structured radiology report (JSON) for the following study evidence:\n\n"
        f"{json.dumps(prompt_dict, indent=2)}\n\n"
        "Remember to adhere strictly to the JSON schema and all safety constraints."
    )
    return user_prompt
